# Generated by Django 3.1.12 on 2025-01-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250106_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
